### PR TITLE
[WIP] Guzzle 6 Support

### PR DESCRIPTION
**Pull request by GrahamCampbell**
TODO:

* [x] Update composer.json
* [ ] Deal with usage of `GuzzleHttp\Post\PostFile` in `Cartalyst\Stripe\Api\FileUploads`
* [ ] Check the guzzle exception stuff will works the same way
* [ ] Deal with `GuzzleHttp\Message\RequestInterface` in `Cartalyst\Stripe\Http\ClientInterface`
* [ ] Update `Cartalyst\Stripe\Http\Cient`

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I've not looked into this in detail, but on first observation it looks a little difficult to support both versions due to the fact we're actually extending the guzzle client class.

**Comment by brunogaspar** [comment]
Not a fan of having this "hacky" way of allowing 2 versions.

Will most likely do a 2.0 with Guzzle 6 support and bump the version on the Laravel bridge package and release a minor, since the API and general usage will hopefully be the same, otherwise a new major will happen on the Laravel package.

Then a 3.0 with a refactor i'm working, that i've no ETA.

Going to close as this is pointing towards 1.0 which is kinda wrong and i prefer to look into this myself.

**Comment by GrahamCampbell** [comment]
> Not a fan of having this "hacky" way of allowing 2 versions.

Me neither.

> Will most likely do a 2.0 with Guzzle 6 support

Great.

> and i prefer to look into this myself.

Sure. How have you got an ETA on that? Also, if you want anything reviewing, feel free to ping me and I'll be happy to help.

**Comment by brunogaspar** [comment]
Hopefully during this week, as it should only take a couple of hours, but i can't promise anything, since it's not a priority and nothing is broken or in an unusable state.

**Comment by GrahamCampbell** [comment]
:)

**Pull request closed without merging**
