### PR TITLE
Test on PHP 7.2-7.4

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Travis doesn't seem to be enabled on this repo, or at least, is not running on PRs, so I don't know if these changes work.

**Comment by brunogaspar** [comment]
It's expected for Travis to not run on pull requests here, since it requires the Stripe key to be set and Travis does not set that key for builds that comes from forked repositories.

But the changes looks good though, so if it breaks it can be fixed, no problem.

**Comment by GrahamCampbell** [comment]
👍 I noticed the collections repo that this package depends on is not tested on travis btw.

**Comment by brunogaspar** [comment]
It's fine, thanks though.

**Comment by GrahamCampbell** [comment]
Looks like stripe is not happy with the test suite smashing their API with the test key. Maybe we should add a concurrency 1 limit into the travis config?

**Comment by brunogaspar** [comment]
Yeah, there's many jobs now.

But ya, i limited it to 2 jobs for now, will push some stuff tomorrow and will see how it goes.

**Comment by GrahamCampbell** [comment]
👍

**Pull request merged**
