### PR TITLE
Guzzle 7 only

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by brunogaspar** [comment]
What about people using Guzzle 6 on their apps?

**Comment by brunogaspar** [comment]
Sorry, i'm blind today, thought this was for 2.x lol

**Comment by GrahamCampbell** [comment]
They can use the 2.x version of this package. 3.x isn't even released yet. Anyway, upgrading to Guzzle 7 from 6 is easy, and the 2.x branch currently allows both versions. ;)

**Comment by GrahamCampbell** [comment]
TBH, moving from Guzzle to PSR-7/17/18 abstractions probably isn't too hard. I could potentially prepare a PR to do this for 3.x if you are interested, Then people can use whatever HTTP client they like.

**Comment by brunogaspar** [comment]
Sure, i would appreciate that, that's actually one of the goals of 3.x.

**Comment by GrahamCampbell** [comment]
I'll create an issue to make sure I don't forget. 👍

**Pull request merged**
