### PR TITLE
IDs can be null

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Without this change, it's not possible to page over all subscriptions.

### CODE REVIEW

**Comment by brunogaspar** [comment]
Thanks.

Will need to check if this still works as expected on another project where i use the pager heavily.

**Comment by GrahamCampbell** [comment]
Sure :)

**Comment by brunogaspar** [comment]
Appear to be fine.

**Comment by brunogaspar** [comment]
Will tag this tomorrow.

Thanks again!

**Comment by GrahamCampbell** [comment]
:rocket:

**Pull request merged**
