### PR TITLE
Support Guzzle 7

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by brunogaspar** [comment]
Waiting on something before making it ready?

**Comment by GrahamCampbell** [comment]
I have not assessed the codebase yet to see what changes are needed, if any. Once I've done that, I'll unmark this as WIP (and make any changes, if needed).

**Comment by brunogaspar** [comment]
Sounds good.

Thanks!

**Comment by GrahamCampbell** [comment]
OK. Got myself a fresh Stripe test account. Time to run the tests using Guzzle 6, and then with Guzzle 7, on my machine. Looking at the code, I think everything should work without any changes.

**Comment by GrahamCampbell** [comment]
All tests passed, both on the run with Guzzle 6.5.2, and the run with Guzzle dev-master.

**Comment by brunogaspar** [comment]
Nice.

We could perhaps make the adjustment on Travis to test on both?

Either way it's cool, going to merge it.

Thanks!

**Pull request merged**
