### PR TITLE
Update Account.php

### PR DESCRIPTION
**Pull request by monove**
removed $params as it is not used for this call and changed to double quotes to use $accountId

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This is a breaking change to the api?

**Comment by monove** [comment]
I tried with the old code and it simply doesn't work

**Comment by GrahamCampbell** [comment]
Depends how strictly we're following semver. It's technically still possible to fix this without changing the method signature.

**Comment by monove** [comment]
True. I'll leave that to you to decide. I tried passing ['id'=>$accountId] as the $parameters array but Stripe failed.

**Comment by brunogaspar** [comment]
The account id is not required, so the method signature is fine as is.

> I tried with the old code and it simply doesn't work

"doesn't work" is very vague.

Just tried here, works perfectly fine.

**Comment by monove** [comment]
It returns the main account, not the account being managed

**Comment by brunogaspar** [comment]
Yap, which is expected, that's on the Stripe docs.

**Comment by monove** [comment]
Initially, you only had one function for Account: details(). That function (as per your spec doc) pulls up details for the owner of the Stripe account, not of any Managed Accounts. I extended it to use other functionality from the Stripe API such as creating/retrieving/updating new Managed Accounts. The find() function should retrieve one specific Managed Account that is not the Stripe owners account.

**Comment by brunogaspar** [comment]
Ok, will have a look into this later.

**Comment by monove** [comment]
https://stripe.com/docs/api#create_account
https://stripe.com/docs/api#retrieve_account
id OPTIONAL
The identifier of the account to be retrieved. If none is provided, will default to the account of the API key.
https://stripe.com/docs/api#update_account
https://stripe.com/docs/api#list_accounts

**Comment by brunogaspar** [comment]
> /account

Works as expected (it's an old API route)

> /accounts

According to the Stripe API docs, this should return what `/account` returns since i'm not passing an identifier, but it doesn't.

> /accounts/:id

Works fine

--

So it seems that the Stripe API is broken or their documentation is incorrect.

**Comment by monove** [comment]
Interesting. How about having the details() function call /account and the find() function call /accounts:id ?

**Comment by brunogaspar** [comment]
Ya, that's what i have at the moment, if you can update the PR with those changes i'll merge it.

I'll open an "issue" on the Stripe forum later in regards of the API endpoint not behaving as expected, unless you want to do so as well.

**Comment by monove** [comment]
https://github.com/cartalyst/stripe/compare/1.0...monove:patch-2

**Comment by monove** [comment]
I'll let you deal with the Stripe forum. Sorry :-(

**Comment by brunogaspar** [comment]
Just update this PR by pushing the changes to the `patch-1` branch, there's no need to create a new PR and you've messed up the spacing there.

**Pull request merged**
