### PR TITLE
Improve Idempotency

### PR DESCRIPTION
**Pull request by brunogaspar**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I wonder if this should instead just set the key on the config object itself (and to avoid any unintended side effects, maybe the config object should be cloned on construction of the client?)

**Comment by brunogaspar** [comment]
hmm but also keep this new behaviour? Otherwise can you elaborate a bit more?

Thanks!

**Comment by GrahamCampbell** [comment]
Wasn't this merged to the wrong branch?

**Comment by brunogaspar** [comment]
Not really, no.

If it's because of BC, that's quite debatable, but it's fine as is IMO as it doesn't break the old behaviour.

**Comment by GrahamCampbell** [comment]
Will the feature be merged up into 2.1 and 2.2 then?

**Comment by brunogaspar** [comment]
Yeap of course.

**Pull request merged**
