### PR TITLE
Support getting all subscriptions without specifying the customer

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by brunogaspar** [comment]
Cool stuff, can you write a simple test for this please?

**Comment by GrahamCampbell** [comment]
Hmm, the tests are failing on Travis.

**Comment by brunogaspar** [comment]
Yeap, it's because of the secret environment variable, not sure that's fixable since Travis prevents those from being leaked, pretty much [this](https://docs.travis-ci.com/user/pull-requests#pull-requests-and-security-restrictions).

Do you have ideas to improve this?

But other than that, don't worry about it failing, i can pull the branch locally and run them.

**Comment by GrahamCampbell** [comment]
Right. So, for me to run the tests, I just need to provide a key to some dummy stripe account I have?

**Comment by brunogaspar** [comment]
Yes, pretty much.

**Comment by GrahamCampbell** [comment]
Sorry for the delay - I will get around to this within the next few days. :)

**Comment by brunogaspar** [comment]
No worries.

I can write the test if you prefer?

**Comment by GrahamCampbell** [comment]
Some aspects of the tests seem to be coupled to the Stripe account congratulation:

```
1) Cartalyst\Stripe\Tests\Api\AccountTest::it_can_retrieve_the_current_account_details
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-US
+GB

/data/tests/Api/AccountTest.php:32
```

**Comment by brunogaspar** [comment]
Kinda expected, since the account i use for tests has the country to be US.

**Comment by GrahamCampbell** [comment]
Alright. I've written a test. :)

**Comment by brunogaspar** [comment]
Awesome. Will tag it later today.

**Pull request merged**
