### PR TITLE
Update Account.php

### PR DESCRIPTION
**Pull request by monove**
Ability to
* Create an account
* Retrieve account details
* Update an account
* List all connected accounts

### CODE REVIEW

**Comment by brunogaspar** [comment]
Thanks :+1:

**Comment by drsii** [comment]
Thanks @monove !

**Comment by monove** [comment]
;-)

**Comment by monove** [comment]
any idea how long it takes for composer to recognize a new commit? I'm still getting 30c8f9f01e0f621bf7c9fa34410849503b849feb

**Comment by brunogaspar** [comment]
Since the latest tag doesn't include this commit, you'll need to add `@dev` to your `composer.json`, something like `"cartalyst/stripe": "~1.0@dev"`.

I'll be tagging this shortly though.

**Pull request merged**
