### PR TITLE
Decouple from Guzzle

### PR DESCRIPTION
**Pull request by GrahamCampbell**
This PR moves us to PSR-17/18 factories.

```
...............................................................  63 / 270 ( 23%)
............................................................... 126 / 270 ( 46%)
.................................SS.SSS........................ 189 / 270 ( 70%)
............................................................... 252 / 270 ( 93%)
..................                                              270 / 270 (100%)
```

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@brunogaspar Ready for a first review now. This PR is fully functional, but documentation will need to be updated.

**Comment by brunogaspar** [comment]
From a quick pass, looks good, there's some minor things here and there.

Going to merge, but don't expect a release very soon, there's still things i want to improve like the current pagination feature, which works but is not efficient for large data sets.

**Comment by GrahamCampbell** [comment]
Regarding pagination, an approach like https://github.com/KnpLabs/php-github-api/pull/907 could work (only probably without the immutability changes).

**Comment by brunogaspar** [comment]
It's not a bad solution the one from that library.

**Pull request merged**
